### ISSUE TITLE
Should I Participate?

### ISSUE THREAD

**Issue by aunyks** [HackGT/catalyst2017-website#8]
Hey guys,

This isn't a real issue; I filed one because I thought I'd get a faster response than email. My questions are as follow:

What's the technical expertise expected for participants in this event? Also, am I allowed to participate since I'm a senior graduating in May?

Thanks in advance.

**Comment by bunsenmcdubbs** [comment]
@aunyks 
Haha awesome! I was briefly very very confused. These are good questions that we are trying to address with better messaging/wording on our site etc.

To answer your question:
1. **No experience needed at all!** None! This event is going to be filled with workshops to introduce and demo stuff that you can continue working on and learning about.
2. Yes! You are in high school and that's all that matters.

**Comment by aunyks** [comment]
@BunsenMcDubbs 
Thanks for the response! 

One more question: I currently have a workable level of programming experience (not to brag but my Github profile is kinda lit 😆 ). Would I stay interested in the workshops throughout the day, since they will be tailored more to beginners?

**Comment by bunsenmcdubbs** [comment]
@aunyks 
Lol yeah I am stalking you now 💯  So we are still working on the details for the workshops right now. The impetus for this event is to get beginners some exposure but that obviously doesn't apply to you. That said, the idea is to have fairly individual/personal environment so we can afford a lot of flexibility on accommodating a variety of skill levels.

Hmu on email (a@andrewdai.co) or [Facebook](https://www.facebook.com/theandrewdai) and lets talk more.

But also you should definitely register anyway if you haven't already 🎆

**Comment by aunyks** [comment]
Bet. I appreciate the help and sorry for asking on Github! I'll keep in touch with you soon.
